apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
        - name: employee-service
          image: nassirsultan/employee-service:latest
          ports:
            - containerPort: 8080
          env: # ← add from here
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: employee-config
                  key: DB_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
