apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employee-service
  template:
    metadata:
      labels:
        app: employee-service
    spec:
      containers:
        - name: employee-service
          image: nassirsultan/employee-service:latest
          ports:
            - containerPort: 8080
